apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: listenertemplates.tekton.dev
spec:
  group: tekton.dev
  version: v1alpha1
  names:
    kind: ListenerTemplate
    plural: listenertemplates
    categories:
    - all
    - tekton-pipelines
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
